const authController=require('../controllers/authController');
const userController=require('../controllers/userController');
const candidateYes=require('../controllers/freeWhatsappCandidateController');
const express = require('express');
const route = express.Router();
const check_auth=require('../middlewares/check_auth');
const check_auth_superadmin=require('../middlewares/check_auth_superadmin');
route.post('/login',authController.login);
route.post('/msmeLogin',authController.msmeLogin);
route.post('/forgetPassword',authController.forgetPassword);
route.post('/changePassword',authController.changePassword);
route.post('/changeMyPassword',check_auth,userController.changeMyPassword);
route.post('/getLogo',check_auth,authController.getLogo);
route.post('/getMyWallet',check_auth,authController.getMyWallet);
route.post("/companyregisteration",authController.companyregisteration);
route.post("/addHiringSupport",check_auth_superadmin,authController.addHiringSupport);
route.post("/contactSales",authController.contactSales);
route.post("/contactDemo",authController.contactDemo);
route.post("/MSMECompanyRegisteration",authController.MSMECompanyRegisteration);
route.post("/changeYesCadidateStatusOpen",candidateYes.changeYesCadidateStatusOpen);
route.post("/updateCrediNoteStatusOpen",candidateYes.updateCrediNoteStatusOpen);
route.post("/updateJoinedStatusOpen",candidateYes.updateJoinedStatusOpen);
route.post("/updateOfferDeclineStatusOpen",candidateYes.updateOfferDeclineStatusOpen);
route.post("/updateOfferDeclineStatusOpen",candidateYes.updateInvoicedStatusOpen);
route.post("/updateOfferDeclineStatusOpen",candidateYes.updateJoiningDitchedStatusOpen);
route.post("/dropCandidateOpen",candidateYes.dropCandidateOpen);
route.post("/updateStcStatusOpen",candidateYes.updateStcStatusOpen);
route.post("/viewCandidateOpen",candidateYes.viewCandidateOpen);
route.post("/getAllCandidateStatusOpen",candidateYes.getAllCandidateStatusOpen);
route.post("/externalViewRequirementsCandidate",authController.externalViewRequirementsCandidate);
route.post("/viewRequirementOpen",authController.viewRequirementOpen);
route.post("/reciveCandidateConformation",candidateYes.reciveCandidateConformation);

module.exports = route;